function [ d_active_dt ] = diff_funk(t,active, params,motif, input,freq)
%DIFF_FUNK Michaelis-Menton kinetic equation
%   ACTIVE is the vector [a_active, b_active, c_active].

if strcmp(input,'init')
    x = .5;
elseif strcmp(input,'up')
    x = .9;
elseif strcmp(input,'down')
    x = .1;
elseif strcmp(input,'osc')
    x = .4*sin(2*pi*freq*t)+.5;
elseif strcmp(input,'init_steposc')
    x = .1;
elseif strcmp(input,'steposc')
    x = .5-.4*cos(2*pi*freq*t);
end


if motif==1
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) + params.kcatafc*active(3)*(1-active(1))/(params.Kmafc+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(2)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==2
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*active(3)*active(1)/(params.Kmar + active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr + active(2));...
        params.kcatcf*active(2)*(1-active(3))/(params.Kmcf + 1 - active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr + active(3))];
    
elseif motif==3
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*params.Ec*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcra*active(1)*active(3)/(params.Kmcra+active(3)) - params.kcatcrb*active(2)*active(3)/(params.Kmcrb+active(3))   ];
    
    
elseif motif==4
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcfa*active(1)*(1-active(3))/(params.Kmcfa+1-active(3)) + params.kcatcfb*active(2)*(1-active(3))/(params.Kmcfb+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==5
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(2)*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==6
    
    d_active_dt = ...
        [ params.kcatafx*x*(1-active(1))/(params.Kmafx+1-active(1))+ params.kcatafb*active(2)*(1-active(1))/(params.Kmafb+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbfa*active(1)*(1-active(2))/(params.Kmbfa+1-active(2)) + params.kcatbfc*active(3)*(1-active(2))/(params.Kmbfc+1-active(2))- params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(2)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==7
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*active(2)*active(1)/(params.Kmar+active(1));...
        params.kcatbfa*active(1)*(1-active(2))/(params.Kmbfa+1-active(2)) + params.kcatbfc*active(3)*(1-active(2))/(params.Kmbfc+1-active(2))- params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*params.Ec*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(2)*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==8
    
    d_active_dt = ...
        [ params.kcatafx*x*(1-active(1))/(params.Kmafx+1-active(1)) + params.kcatafb*active(2)*(1-active(1))/(params.Kmafb+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*active(3)*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(2)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==9
    
    d_active_dt = ...
        [ params.kcatafx*x*(1-active(1))/(params.Kmafx+1-active(1)) + params.kcatafc*active(3)*(1-active(1))/(params.Kmafc+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcfa*active(1)*(1-active(3))/(params.Kmcfa+1-active(3)) + params.kcatcfb*active(2)*(1-active(3))/(params.Kmcfb+1-active(3))- params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3))  ];
    
elseif motif==10
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*active(3)*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(2)*(active(3))/(params.Kmcr+active(3))];
    
elseif motif==11
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*active(3)*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcfa*active(1)*(1-active(3))/(params.Kmcfa+1-active(3)) + params.kcatcfb*active(2)*(1-active(3))/(params.Kmcfb+1-active(3)) - params.kcatcr*params.Fc*(active(3))/(params.Kmcr+active(3))];
    
elseif motif==12
    
    d_active_dt = ...
        [ params.kcatafx*x*(1-active(1))/(params.Kmafx+1-active(1)) + params.kcatafc*active(3)*(1-active(1))/(params.Kmafc+1-active(1))- params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(2)*(active(3))/(params.Kmcr+active(3))];
    
elseif motif==13
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*active(3)*active(2)/(params.Kmbr+active(2));...
        params.kcatcfa*active(1)*(1-active(3))/(params.Kmcfa+1-active(3)) + params.kcatcfb*active(2)*(1-active(3))/(params.Kmcfb+1-active(3))  - params.kcatcr*params.Fc*(active(3))/(params.Kmcr+active(3))];
    
elseif motif==14
    
    d_active_dt = ...
        [ params.kcatafx*x*(1-active(1))/(params.Kmafx+1-active(1)) + params.kcatafc*active(3)*(1-active(1))/(params.Kmafc+1-active(1))- params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*active(3)*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(2)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(1)*(active(3))/(params.Kmcr+active(3))];
    
elseif motif==15
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3));...
        params.kcatdfb*active(2)*(1-active(4))/(params.Kmdfb+1-active(4)) + params.kcatdfc*active(3)*(1-active(4))/(params.Kmdfc+1-active(4)) - params.kcatdr*params.Fd*(active(4))/(params.Kmdr+active(4))];
    
elseif motif==16
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3));...
        params.kcatdf*active(2)*(1-active(4))/(params.Kmdf+1-active(4)) - params.kcatdr*active(3)*(active(4))/(params.Kmdr+active(4))];
    
elseif motif==17
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*params.Ec*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(1)*active(3)/(params.Kmcr+active(3));...
        params.kcatdfb*active(2)*(1-active(4))/(params.Kmdfb+1-active(4)) + params.kcatdfc*active(3)*(1-active(4))/(params.Kmdfc+1-active(4)) - params.kcatdr*params.Kmdr*(active(4))/(params.Kmdr+active(4))];
    
elseif motif==18
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*params.Ec*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(1)*active(3)/(params.Kmcr+active(3));...
        params.kcatdf*active(3)*(1-active(4))/(params.Kmdf+1-active(4)) - params.kcatdr*active(2)*active(4)/(params.Kmdr+active(4))];
    
elseif motif==19
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*params.Ec*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(1)*active(3)/(params.Kmcr+active(3));...
        params.kcatdf*active(2)*(1-active(4))/(params.Kmdf+1-active(4)) - params.kcatdr*active(3)*active(4)/(params.Kmdr+active(4))];
    
elseif motif==20
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3));...
        params.kcatdf*params.Ed*(1-active(4))/(params.Kmdf+1-active(4)) - params.kcatdrb*active(2)*active(4)/(params.Kmdrb+active(4)) - params.kcatdrc*active(3)*active(4)/(params.Kmdrc+active(4))];
    
    
elseif any(motif==21:2)
    y = 0.5+(t>=0)*.4; %a step up.
    
    if motif==21
        
        d_active_dt = ...
            [params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
            params.kcatbf*y*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
            params.kcatcfa*active(1)*(1-active(3))/(params.Kmcfa+1-active(3))+params.kcatcfb*active(2)*(1-active(3))/(params.Kmcfb+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3));...
            params.kcatdfa*active(1)*(1-active(4))/(params.Kmdfa+1-active(4))+ params.kcatdfb*active(2)*(1-active(4))/(params.Kmdfb+1-active(4)) - params.kcatdr*params.Fd*active(4)/(params.Kmdr+active(4));...
            params.kcatefc*active(3)*(1-active(5))/(params.Kmefc+1-active(5))+ params.kcatefd*active(4)*(1-active(5))/(params.Kmefd+1-active(5)) - params.kcater*params.Fe*active(5)/(params.Kmer+active(5))];
        
    elseif motif == 22
        d_active_dt = ...
            [params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
            params.kcatbf*y*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
            params.kcatcfa*active(1)*(1-active(3))/(params.Kmcfa+1-active(3))+params.kcatcfb*active(2)*(1-active(3))/(params.Kmcfb+1-active(3)) - params.kcatcr*params.Fc*active(3)/(params.Kmcr+active(3));...
            params.kcatdf*active(2)*(1-active(4))/(params.Kmdf+1-active(4))- params.kcatdr*active(1)*active(4)/(params.Kmdr+active(4));...
            params.kcatefc*active(3)*(1-active(5))/(params.Kmefc+1-active(5))+ params.kcatefd*active(4)*(1-active(5))/(params.Kmefd+1-active(5)) - params.kcater*params.Fe*active(5)/(params.Kmer+active(5))];
        
    elseif motif == 23
        d_active_dt = ...
            [params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
            params.kcatbf*y*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
            params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(2)*active(3)/(params.Kmcr+active(3));...
            params.kcatdf*active(2)*(1-active(4))/(params.Kmdf+1-active(4))- params.kcatdr*active(1)*active(4)/(params.Kmdr+active(4));...
            params.kcatefc*active(3)*(1-active(5))/(params.Kmefc+1-active(5))+ params.kcatefd*active(4)*(1-active(5))/(params.Kmefd+1-active(5)) - params.kcater*params.Fe*active(5)/(params.Kmer+active(5))];
    
     elseif motif == 24
        d_active_dt = ...
            [params.kcatbf*x*(1-active(1))/(params.Kmbf+1-active(1)) - params.kcatbr*params.Fa*active(1)/(params.Kmbr+active(1));...
            params.kcatcf*y*(1-active(2))/(params.Kmcf+1-active(2)) - params.kcatcr*params.Fb*active(2)/(params.Kmbr+active(2));...
            params.kcatcf*active(1)*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(2)*active(3)/(params.Kmcr+active(3));...
            params.kcatdf*active(2)*(1-active(4))/(params.Kmdf+1-active(4))- params.kcatdr*active(1)*active(4)/(params.Kmdr+active(4));...
            params.kcatefc*active(3)*(1-active(5))/(params.Kmefc+1-active(5))+ params.kcatefd*active(4)*(1-active(5))/(params.Kmefd+1-active(5)) - params.kcater*params.Fe*active(5)/(params.Kmer+active(5))];
    end
    
elseif motif==1819
    
    d_active_dt = ...
        [ params.kcataf*x*(1-active(1))/(params.Kmaf+1-active(1)) - params.kcatar*params.Fa*active(1)/(params.Kmar+active(1));...
        params.kcatbf*active(1)*(1-active(2))/(params.Kmbf+1-active(2)) - params.kcatbr*params.Fb*active(2)/(params.Kmbr+active(2));...
        params.kcatcf*params.Ec*(1-active(3))/(params.Kmcf+1-active(3)) - params.kcatcr*active(1)*active(3)/(params.Kmcr+active(3));...
        params.kcatdf*active(3)*(1-active(4))/(params.Kmdf+1-active(4)) - params.kcatdr*active(2)*active(4)/(params.Kmdr+active(4));
        params.kcatef*active(4)*(1-active(5))/(params.Kmef+1-active(5)) - params.kcater*params.Fe*active(5)/(params.Kmer+active(5));...
        params.kcatff*active(5)*(1-active(6))/(params.Kmff+1-active(6)) - params.kcatfr*params.Ff*active(6)/(params.Kmfr+active(6));...
        params.kcatgf*params.Eg*(1-active(7))/(params.Kmgf+1-active(7)) - params.kcatgr*active(5)*active(7)/(params.Kmgr+active(7));...
        params.kcathf*active(6)*(1-active(8))/(params.Kmhf+1-active(8)) - params.kcathr*active(7)*active(8)/(params.Kmhr+active(8))];
    
    
end





end